#define KEYWORD 1
#define IDENTIFIER 2
#define INTEGERCONSTANT 3
#define FLOATINGCONSTANT 4
#define CHARACTERCONSTANT 5
#define STRINGLITERAL 6
#define PUNCTUATOR 7
#define COMMENT 8
#define SINGLELINECOMMENT 9
#define MULTILINECOMMENT 10
#define UNEXPECTED 9


